name: Build & Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
      - name: Build Chata
        run: |
          just build
          echo "Now building the libchata example..."
          cd libchata
          g++ -std=c++20 ultrassembler_example.cpp -lchata
          echo "Success"
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to ~/.local/bin
          export PATH=$HOME/.local/bin:$PATH
      - name: Test Chata
        run: |
          just build
          just test